server:
  port: 8080

spring:
  application:
    name: EdumalProject
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: jdbc:mysql://localhost:3306/edumalldb
    username: root
    password: hung2002
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
    web: INFO